### ISSUE TITLE
http://validator.w3.org/check?uri=referer Not working properly

### ISSUE THREAD

**Issue by wmmead** [w3c/markup-validator#51] opened 2021-02-01 14:16 UTC
Putting this link at the bottom of a page and clicking it results in checking the validity of the default file in the domain rather than the specific file to be checked.

valid HTML

For example: When the link is clicked on the page at https://examplesite.com/testing.html the file that is tested is https://examplesite.com/index.html

**Comment by dontcallmedom** [comment] 2022-04-07 06:55
closing this as duplicate of #34

**Closed by dontcallmedom** 2022-04-07 06:55 UTC
